name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup rokit
        uses: CompeyDev/setup-rokit@v0.2.1

      - name: Install dependencies
        run: |
          pesde install

      - name: Setup lute
        run: |
          lute setup

      - name: Build
        run: |
          lute run build
